[package]
name = "flydoc"
version = "1.0.1"

[dependencies]
flylibc = { git="git@github.com:drewagislason/flylibc.git" }
# flylibc = { path="../flylibc/lib/flylibc.a", inc="../flylibc/inc" }
# flylibc = { path="../flylibc/" }
